---
apiVersion: hive.openshift.io/v1
kind: ClusterClaim
metadata:
  name: jnp-azure-01
  namespace: my-pools
  labels:
    usage: development
    cluster.open-cluster-management.io/clusterset: all-clusters
spec:
  clusterPoolName: azure-centralus  # Create a cluster pool using the Infrastructure > Clusters > Cluster pools console
